# messy_analysis.py -- the Lesson 5 refactoring exercise starts here.
#
# This script WORKS. Run it from inside lesson5_exercise/ :
#
#     python3 messy_analysis.py
#
# It prints correct numbers. It is also everything Lesson 5 warned about:
# no functions, copy-pasted paragraphs, magic numbers, a deeply nested loop,
# and print() where a return should be. Your job (see README.md) is to
# refactor it into analysis.py WITHOUT changing any number it computes.
# Do not edit THIS file -- it is your reference for correct behavior.

import pandas as pd

data = pd.read_csv("../course_data/online_retail_sample.csv")
print("rows loaded:", len(data))

data["Description"] = data["Description"].str.strip()
data["revenue"] = data["Quantity"] * data["UnitPrice"]

# drop the cheap stuff
data = data[data["UnitPrice"] >= 1.0]
data = data.reset_index(drop=True)
print("rows kept after price cleaning:", len(data))
print()

# revenue for United Kingdom
uk_total = 0
for i in range(len(data)):
    if data.loc[i, "Country"] == "United Kingdom":
        uk_total = uk_total + data.loc[i, "revenue"]
print("United Kingdom revenue:", round(uk_total, 2))

# revenue for EIRE
eire_total = 0
for i in range(len(data)):
    if data.loc[i, "Country"] == "EIRE":
        eire_total = eire_total + data.loc[i, "revenue"]
print("EIRE revenue:", round(eire_total, 2))

# revenue for Netherlands
nl_total = 0
for i in range(len(data)):
    if data.loc[i, "Country"] == "Netherlands":
        nl_total = nl_total + data.loc[i, "revenue"]
print("Netherlands revenue:", round(nl_total, 2))
print()

# figure out the top 3 customers
customer_ids = []
for i in range(len(data)):
    if data.loc[i, "source_customer_id"] not in customer_ids:
        customer_ids.append(data.loc[i, "source_customer_id"])

totals = []
for c in customer_ids:
    t = 0
    for i in range(len(data)):
        if data.loc[i, "source_customer_id"] == c:
            t = t + data.loc[i, "revenue"]
    totals.append(round(t, 2))

print("top 3 customers:")
for rank in range(3):
    best_pos = -1
    for j in range(len(customer_ids)):
        if totals[j] is None:
            continue
        if best_pos == -1:
            best_pos = j
        elif totals[j] > totals[best_pos]:
            best_pos = j
        elif totals[j] == totals[best_pos] and customer_ids[j] < customer_ids[best_pos]:
            best_pos = j
    print("  #" + str(rank + 1), "customer", customer_ids[best_pos], "spent", totals[best_pos])
    totals[best_pos] = None
